version: "3.8"
services:
  web:
    container_name: BudgetEquanimity_Django_Server
    build: ./app
    command: bash -c "python -m pip install --upgrade pip && python -m pip install
      -r requirements.txt && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - DB_NAME=budget_equanimity
      - DB_USER=[DATABASE USER]
      - DB_PASSWORD=[DATBASE PASSWORD]
      - DB_HOST=[DATABASE HOST NAME]
      - DB_PORT=5432
      - DATABASE=budget_equanimity
    depends_on:
      - pg
  pg:
    container_name: BudgetEquanimity_pg_container
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: budget_equanimity
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - ./data/misc/init.sql:/docker-entrypoint-initdb.d/1-init.sql
  pgadmin:
    container_name: BudgetEquanimity_pgadmin_container
    image: dpage/pgadmin4:5.2
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: passwordExample
      PGADMIN_LISTEN_PORT: 5433
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    ports:
      - "5433:5433"
    depends_on:
      - pg
